# .github/workflows/build.yml
name: Build and Attest

on:
  workflow_run:
    workflows:
      - "Build and Publish Docker Image"   # must exactly match docker-publish.yml’s `name:`
    types:
      - completed

jobs:
  release:
    # only run if the upstream job actually succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v4
      - uses: tinfoilsh/pri-build-action@v0.1.2
        with:
          config-file: ${{ github.workspace }}/tinfoil-config.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
